language:go
go:
-1.8
-tip

sudo:false

install:  
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  

#notifications:
 # webhooks:
  #  urls:
   #   - https://webhooks.gitter.im/e/67e4b42cbf763625d0b4
    #on_success: change
    #on_failure: always
    #on_start: never