sudo: false
language: go
go:
- 1.6.2
env:
  global:
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"
  - GOPATH ="$HOME/gopath/src/github.com/balaweblog/gosqlapi;$HOME/gopath"
before_script:
    - echo GOPATH
before_install:
- go get github.com/go-sql-driver/mysql
- go get golang.org/x/tools/cmd/cover