language:go
 environment:
          - GOPATH=$HOME/gopath/src/github.com/balaweblog/gosqlapi
go:
-1.8
-tip

sudo:false


  
  

#notifications:
 # webhooks:
  #  urls:
   #   - https://webhooks.gitter.im/e/67e4b42cbf763625d0b4
    #on_success: change
    #on_failure: always
    #on_start: never