language: go

sudo: false

go:
    - 1.6
    - 1.7
    - tip

before_install:
    - go get github.com/balaweblog/gosqlapi/model
    - go get github.com/balaweblog/gosqlapi/handlers
    - go get github.com/balaweblog/gosqlapi/logger
    - go get github.com/balaweblog/gosqlapi/routers
    - go get github.com/gorilla/mux
    - go get github.com/go-sql-driver/mysql

install:
    - go get -d -v ./...